name: Release

on:
  push:
    paths: 
      - package.json
    branches:
      - main
      - v1
      
jobs:

  build-and-publish:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    environment: 'prod'

    steps:
      - uses: actions/checkout@v4

      - uses: prefecthq/actions-release-ui-components@main
        id: release-ui-components
        with:
          NPM_TOKEN: ${{ secrets.PREFECT_UI_COMPONENTS_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: prefecthq/actions-trigger-downstream-npm-package-updates@main
        id: trigger-downstream-npm-package-update-prefect-ui-library
        if: ${{ steps.release-ui-components.outputs.type }}
        with:
          GITHUB_TOKEN: ${{ secrets.PREFECT_UI_LIBRARY_ACTIONS_RW }}
          DOWNSTREAM_REPO_NAME: prefect-ui-library
          RELEASE_TAG: ${{ steps.release-ui-components.outputs.version}}
